name: CD Pipeline

on:
  workflow_run:
    workflows: ["CI Pipeline"]
    types:
      - completed

jobs:
  build:
    runs-on: self-hosted

    steps:
      - name: Pull Docker image
        run: sudo docker pull murfo/cryptarch-quiz:latest
      - name: Delete Old docker container
        run: sudo docker rm -f cryptarch-quiz-container || true
      - name: Run Docker Container
        run: sudo docker run -d -p 8000:8000 --name cryptarch-quiz-container murfo/cryptarch-quiz
